version: "2.2"
services:
    jobmanager:
        image: flink:latest
        container_name: flink_jobmanager
        ports:
            - "8081:8081"
        command: jobmanager
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager
        volumes:
            - /Users/monkey/development/data_engineering/flink-examples/batch/build/libs:/jars
            - /Users/monkey/development/data_engineering/flink-examples/batch/data:/data
            - /Users/monkey/development/data_engineering/flink-examples/batch/output:/output

    taskmanager:
        image: flink:latest
        container_name: flink_taskmanager
        depends_on:
            - jobmanager
        command: taskmanager
        scale: 1
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager
                taskmanager.numberOfTaskSlots: 2
        volumes:
            - /Users/monkey/development/data_engineering/flink-examples/batch/data:/data
            - /Users/monkey/development/data_engineering/flink-examples/batch/output:/output
