/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.martishin.flinkbatch;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DataBatchJobTest {
    @Test void appHasAGreeting() {
        DataBatchJob classUnderTest = new DataBatchJob();
        assertNotNull(classUnderTest, "app should be able to run");
    }
}
